POST http://localhost:8080/ci/docker/build
Content-Type: application/json

{
  "dockerTag": "event-bus:v1",
  "type": "maven",
  "gitCloneParam": {
    "repository": "https://gitee.com/synuwxy/event-bus.git",
    "branch": "master"
  }
}

###
